name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: generated/profile.svg
  
      - uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: generated/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_indepth: true
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 100
          plugin_languages_analysis_timeout: 60

      - uses: lowlighter/metrics@latest
        with:
          filename: generated/wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
